lobby:
  spawn_pos:
    world: pb_lobby
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
all_levels:
  POSITIVE_X:
    min_editable_point: "-32 0 0"
    max_editable_point: "35000 255 15"
  NEGATIVE_X:
    min_editable_point: "-35000 0 0"
    max_editable_point: "32 255 15"
