lobby:
  spawn_pos:
    world: pb_lobby
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
all_levels:
  min_editable_point: "-32 0 0"
  max_editable_point: "35000 255 15"
default_level:
  direction: POSITIVE_X
  start_point: "0.0 5.0 0.0"
  finish_point: "10.0 5.0 0.0"
  spawn_pos:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
