name: ParkourBeat
main: ru.sortix.parkourbeat.ParkourBeat
version: 0.5
api-version: 1.13
author: Sortix, Bomb
depend: [ AMusic ]
commands:
  spawn:
    aliases:
      - 'hub'
      - 'lobby'
  tptoworld:
  play:
  edit:
  create:
  delete:
  color:
  song:
  test:
